# -*- coding: utf-8 -*-
"""__init__.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fX5W2gcD85YKrg-Qhndux8_d2RZqMP0u
"""

is_simple_core = False

if is_simple_core:
  from dezero.core_simple import Variable
  from dezero.core_simple import Function
  from dezero.core_simple import using_config
  from dezero.core_simple import no_grad
  from dezero.core_simple import as_array
  from dezero.core_simple import as_variable
  from dezero.core_simple import setup_variable

else:
  from dezero.core import Variable
  from dezero.core import Function
  from dezero.core import using_config
  from dezero.core import no_grad
  from dezero.core import as_array
  from dezero.core import as_variable
  from dezero.core import setup_variable

  import dezero.functions
  import dezero.utils



setup_variable()

#__init__.py는 패티지에 속한 모듈 임포트할 때 가장 먼저 실행되는 파일
# 이후로 from dezero.core_simple import Variable 가 아니라
# from dezero import Variable 라고 간략하게 입력 가능